import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { io, Socket } from "socket.io-client";
import { ArrowLeft, Bell, Check, CheckCheck, ChevronDown, Image, LogOut, Menu, MessageCircle, MoreHorizontal, Paperclip, Phone, Plus, Search, Send, Smile, Sparkles, Users, Video, X } from "lucide-react";
import "./styles.css";

type User = { id: string; email: string; name: string; avatarUrl?: string | null };
type Message = { id: string; body: string; senderId: string; conversationId?: string; createdAt: string; sender?: User; reactions?: { emoji: string; userId: string }[] };
type Conversation = { id: string; name?: string | null; isGroup: boolean; members: { user: User }[]; messages?: Message[] };
const API = import.meta.env.VITE_API_URL ?? "http://localhost:4000";
const demoUser: User = { id: "demo", email: "demo@friendschat.local", name: "Alex Morgan" };
const demoConversations: Conversation[] = [
  { id: "c1", name: "Design crew", isGroup: true, members: [{ user: demoUser }, { user: { id: "u2", email: "", name: "Maya Chen" } }, { user: { id: "u3", email: "", name: "Noah Williams" } }], messages: [{ id: "m1", body: "The new profile flow is looking great ✨", senderId: "u2", createdAt: new Date(Date.now() - 3600000).toISOString() }, { id: "m2", body: "Thanks! I’ll share the prototype after lunch.", senderId: "demo", createdAt: new Date(Date.now() - 3000000).toISOString() }] },
  { id: "c2", name: "Maya Chen", isGroup: false, members: [{ user: demoUser }, { user: { id: "u2", email: "", name: "Maya Chen" } }], messages: [{ id: "m3", body: "Are we still on for coffee tomorrow?", senderId: "u2", createdAt: new Date(Date.now() - 86400000).toISOString() }] },
  { id: "c3", name: "Weekend plans", isGroup: true, members: [{ user: demoUser }, { user: { id: "u4", email: "", name: "Priya Patel" } }], messages: [] }
];

async function request<T>(path: string, init: RequestInit = {}, token?: string): Promise<T> {
  const response = await fetch(`${API}${path}`, { ...init, headers: { "content-type": "application/json", ...(token ? { authorization: `Bearer ${token}` } : {}), ...(init.headers ?? {}) } });
  if (!response.ok) throw new Error((await response.json().catch(() => null))?.error ?? "Request failed");
  return response.json();
}

function Avatar({ name, small = false }: { name: string; small?: boolean }) {
  return <div className={`grid shrink-0 place-items-center rounded-full bg-gradient-to-br from-violet-400 to-fuchsia-500 font-semibold text-white ${small ? "h-8 w-8 text-xs" : "h-11 w-11 text-sm"}`}>{name.split(" ").map((p) => p[0]).join("").slice(0, 2)}</div>;
}

function Auth({ onLogin }: { onLogin: (user: User, token?: string) => void }) {
  const [register, setRegister] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); try { const data = await request<{ user: User; token: string }>(register ? "/auth/register" : "/auth/login", { method: "POST", body: JSON.stringify(register ? { name, email, password } : { email, password }) }); localStorage.setItem("friendschat-token", data.token); onLogin(data.user, data.token); } catch { onLogin({ ...demoUser, name: name || demoUser.name, email: email || demoUser.email }); } }
  return <main className="grid min-h-screen place-items-center bg-[#f4f2ff] px-5"><div className="w-full max-w-md rounded-[2rem] bg-white p-8 shadow-soft"><div className="mb-8 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-lavender text-white"><MessageCircle size={23} /></div><div><p className="text-xl font-bold text-ink">FriendsChat</p><p className="text-xs text-slate-400">Conversations, beautifully simple.</p></div></div><h1 className="mb-2 text-2xl font-bold text-ink">{register ? "Create your account" : "Welcome back"}</h1><p className="mb-6 text-sm text-slate-500">{register ? "Start chatting with your people." : "Sign in to pick up where you left off."}</p><form onSubmit={submit} className="space-y-4">{register && <input className="field" placeholder="Your name" value={name} onChange={(e) => setName(e.target.value)} required />}<input className="field" type="email" placeholder="Email address" value={email} onChange={(e) => setEmail(e.target.value)} required /><input className="field" type="password" placeholder="Password (8+ characters)" value={password} onChange={(e) => setPassword(e.target.value)} minLength={8} required />{error && <p className="text-sm text-rose-500">{error}</p>}<button className="primary w-full">{register ? "Create account" : "Sign in"} <ArrowLeft className="rotate-180" size={16} /></button></form><button onClick={() => setRegister(!register)} className="mt-6 w-full text-sm text-slate-500 hover:text-lavender">{register ? "Already have an account? Sign in" : "New here? Create an account"}</button><p className="mt-5 text-center text-xs text-slate-400">Demo mode is available when the API is offline.</p></div></main>;
}

function App() {
  const [user, setUser] = useState<User | null>(null); const [token, setToken] = useState(localStorage.getItem("friendschat-token") ?? undefined); const [conversations, setConversations] = useState<Conversation[]>([]); const [activeId, setActiveId] = useState<string | null>(null); const [query, setQuery] = useState(""); const [socket, setSocket] = useState<Socket | null>(null);
  useEffect(() => { if (!token) return; request<{ user: User }>("/auth/me", {}, token).then((x) => setUser(x.user)).catch(() => setUser(demoUser)); }, [token]);
  useEffect(() => { if (!user) return; request<Conversation[]>("/conversations", {}, token).then(setConversations).catch(() => setConversations(demoConversations)); }, [user, token]);
  useEffect(() => { if (!token || !user?.id || user.id === "demo") return; const s = io(API, { auth: { token } }); s.on("message:new", (message: Message) => setConversations((all) => all.map((c) => c.id === message.conversationId ? { ...c, messages: [...(c.messages ?? []), message] } : c))); setSocket(s); return () => { s.disconnect(); }; }, [token, user]);
  const visible = useMemo(() => conversations.filter((c) => (c.name ?? c.members.find((m) => m.user.id !== user?.id)?.user.name ?? "").toLowerCase().includes(query.toLowerCase())), [conversations, query, user]);
  if (!user) return <Auth onLogin={(u, t) => { setUser(u); setToken(t); }} />;
  return <div className="flex h-screen overflow-hidden bg-mist text-ink"><Sidebar user={user} conversations={visible} activeId={activeId} query={query} setQuery={setQuery} onSelect={setActiveId} onLogout={() => { localStorage.removeItem("friendschat-token"); setUser(null); }} /><Chat conversation={conversations.find((c) => c.id === activeId) ?? null} user={user} token={token} socket={socket} onMessage={(message) => setConversations((all) => all.map((c) => c.id === activeId ? { ...c, messages: [...(c.messages ?? []), message] } : c))} /></div>;
}

function Sidebar({ user, conversations, activeId, query, setQuery, onSelect, onLogout }: { user: User; conversations: Conversation[]; activeId: string | null; query: string; setQuery: (x: string) => void; onSelect: (x: string) => void; onLogout: () => void }) {
  return <aside className="flex w-full max-w-[340px] flex-col border-r border-slate-200 bg-white"><div className="flex items-center justify-between px-6 pb-4 pt-6"><div className="flex items-center gap-3"><Avatar name={user.name} /><div><p className="font-semibold">{user.name}</p><p className="flex items-center gap-1 text-xs text-emerald-500"><span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />Online</p></div></div><button className="icon-btn" title="Sign out" onClick={onLogout}><LogOut size={17} /></button></div><div className="px-5 pb-5"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17} /><input className="field h-11 pl-10" placeholder="Search conversations" value={query} onChange={(e) => setQuery(e.target.value)} /></div></div><div className="flex items-center justify-between px-6 pb-3"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Messages</p><button className="icon-btn h-8 w-8 bg-violet-50 text-lavender"><Plus size={17} /></button></div><div className="scrollbar-hide flex-1 overflow-y-auto px-3">{conversations.map((conversation) => { const other = conversation.members.find((m) => m.user.id !== user.id)?.user; const label = conversation.name ?? other?.name ?? "Conversation"; const last = conversation.messages && conversation.messages.length ? conversation.messages[conversation.messages.length - 1] : undefined; return <button key={conversation.id} onClick={() => onSelect(conversation.id)} className={`flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-left transition ${activeId === conversation.id ? "bg-violet-50" : "hover:bg-slate-50"}`}><Avatar name={label} small /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-semibold">{label}</p><span className="text-[10px] text-slate-400">{last ? new Date(last.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }) : ""}</span></div><p className="truncate text-xs text-slate-500">{last?.body ?? "Start a conversation"}</p></div></button>; })}</div><div className="m-4 rounded-2xl bg-[#f7f5ff] p-4"><div className="mb-2 flex items-center gap-2 text-lavender"><Sparkles size={16} /><span className="text-xs font-bold">FriendsChat Plus</span></div><p className="text-xs leading-relaxed text-slate-500">Share GIFs, stickers and files with your closest people.</p></div></aside>;
}

function Chat({ conversation, user, token, socket, onMessage }: { conversation: Conversation | null; user: User; token?: string; socket: Socket | null; onMessage: (m: Message) => void }) {
  const [draft, setDraft] = useState(""); const [sending, setSending] = useState(false); const messages = conversation?.messages ?? []; const title = conversation?.name ?? conversation?.members.find((m) => m.user.id !== user.id)?.user.name ?? "Select a conversation";
  useEffect(() => { if (conversation && socket) { socket.emit("conversation:join", conversation.id); return () => { socket.emit("conversation:leave", conversation.id); }; } }, [conversation, socket]);
  async function send() { if (!draft.trim() || !conversation || sending) return; setSending(true); const body = draft.trim(); setDraft(""); try { const message = await request<Message>(`/conversations/${conversation.id}/messages`, { method: "POST", body: JSON.stringify({ body }) }, token); onMessage(message); } catch { onMessage({ id: crypto.randomUUID(), body, senderId: user.id, createdAt: new Date().toISOString(), sender: user }); } finally { setSending(false); } }
  if (!conversation) return <main className="hidden flex-1 place-items-center md:grid"><div className="text-center"><div className="mx-auto mb-4 grid h-16 w-16 place-items-center rounded-3xl bg-violet-100 text-lavender"><MessageCircle size={30} /></div><h2 className="text-lg font-bold">Your conversations</h2><p className="mt-1 text-sm text-slate-400">Choose a chat to start messaging.</p></div></main>;
  return <main className="flex min-w-0 flex-1 flex-col"><header className="flex h-[82px] items-center justify-between border-b border-slate-200 bg-white px-5 md:px-8"><div className="flex items-center gap-3"><Avatar name={title} small /><div><h1 className="font-bold">{title}</h1><p className="text-xs text-emerald-500">{conversation.isGroup ? `${conversation.members.length} members` : "Active now"}</p></div></div><div className="flex gap-1"><button className="icon-btn"><Phone size={18} /></button><button className="icon-btn"><Video size={18} /></button><button className="icon-btn"><MoreHorizontal size={18} /></button></div></header><div className="scrollbar-hide flex-1 overflow-y-auto px-5 py-6 md:px-12">{messages.map((message, i) => { const mine = message.senderId === user.id; return <div key={message.id} className={`mb-5 flex items-end gap-2 ${mine ? "justify-end" : "justify-start"}`}>{!mine && <Avatar name={message.sender?.name ?? conversation.members.find((m) => m.user.id === message.senderId)?.user.name ?? "Friend"} small />}<div className={`max-w-[75%] md:max-w-[60%] ${mine ? "items-end" : "items-start"} flex flex-col`}><div className={`rounded-2xl px-4 py-3 text-sm leading-relaxed ${mine ? "rounded-br-md bg-lavender text-white" : "rounded-bl-md bg-white shadow-sm"}`}>{message.body}</div><div className="mt-1 flex items-center gap-1 text-[10px] text-slate-400">{new Date(message.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}{mine && (i === messages.length - 1 ? <CheckCheck size={13} className="text-lavender" /> : <Check size={13} />)}</div></div></div>; })}</div><div className="border-t border-slate-200 bg-white px-5 py-4 md:px-8"><div className="flex items-center gap-2 rounded-2xl bg-mist p-2"><button className="icon-btn"><Paperclip size={19} /></button><input className="min-w-0 flex-1 bg-transparent px-2 text-sm outline-none" placeholder="Write a message..." value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") void send(); }} /><button className="icon-btn hidden sm:grid"><Smile size={19} /></button><button className="icon-btn hidden sm:grid"><Image size={19} /></button><button onClick={() => void send()} disabled={!draft.trim() || sending} className="grid h-10 w-10 place-items-center rounded-xl bg-lavender text-white transition hover:bg-violet-700 disabled:opacity-40"><Send size={17} /></button></div><p className="mt-2 text-center text-[10px] text-slate-400">Messages are encrypted in transit · Press Enter to send</p></div></main>;
}

if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("/sw.js"));
createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
